version: "2.1"
services:
    dashboard-frontend:
        build: ./frontend/
        environment: 
            HOST: "0.0.0.0"
            PORT: 80
        command: "yarn start"
        ports:
          - "80:80"
        volumes:
          - ./env-frontend-dev:/app/.env
        networks:
          - pocket
    dashboard-backend:
        build: ./backend/
        ports:
          - "4200:4200"
        depends_on:
          - "mongodb"
          - "redis"
        volumes:
          - ./env-backend-dev:/app/.env
        networks:
          - pocket
    mongodb:
        image: mongo:3.2.11
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongo-client
            MONGO_INITDB_ROOT_PASSWORD: mongo-password
        volumes: 
          - ~/.pocket/mongodb:/data/db
        ports:
          - "27017:27017"
        networks:
          - pocket
    redis:
        image: "redis:alpine"
        command: redis-server
        ports:
          - "6379:6379"
        volumes:
          - ~/.pocket/redis:/var/lib/redis
          - ./redis.conf:/usr/local/etc/redis/redis.conf
        environment:
          - REDIS_REPLICATION_MODE=master
        networks:
          - pocket
    gateway:
        image: "gateway:latest"
        ports:
          - "3000:3000"
        depends_on:
          - "mongodb"
          - "redis"
        volumes:
          - ./env-gateway-dev:/home/node/app/.env
        networks:
          - pocket
networks:
    pocket:
        driver: bridge
