# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pocket Daskboard CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

env:
  DOCKER_REPOSITORY: poktnetwork/pocket-dashboard
  DOCKER_BACKEND_PORT: 4200

jobs:
  # Backend CI
  Backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    services:
      localhost:
        image: mongo:4.2
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: backend
        run: yarn

      - name: Running lint
        working-directory: backend
        run: yarn lint

      - name: Running testing
        working-directory: backend
        run: yarn test

      - name: Running prod build
        working-directory: backend
        run: yarn build:prod

  Backend-Docker:
    needs: Backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Docker image
        working-directory: backend
        run: docker build --build-arg PORT=${{ env.DOCKER_BACKEND_PORT }} --tag ${{ env.DOCKER_REPOSITORY }}:${{ github.ref }} .
      - name: Push Docker image
        run: docker push ${{ env.DOCKER_REPOSITORY }}:${{ github.ref }}

  # Frontend CI
  Frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: frontend
        run: yarn

      - name: Running lint
        working-directory: frontend
        run: yarn lint

      - name: Running prod build
        working-directory: frontend
        run: yarn build:prod

        env:
          CI: true
