name: Production Deployment

on:
  push:
    branches: [ staging ]

jobs:
  build:
    name: Frontend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.15.0 ]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn
      working-directory: frontend
      run: yarn
    - name: Production build
      working-directory: frontend
      env:
        GENERATE_SOURCEMAP: false
        PUBLIC_URL: https://dashboard.pokt.network
        REACT_APP_BACKEND_URL: https://api.dashboard.pokt.network:4200
        REACT_APP_POCKET_NETWORK_MAX_DISPATCHER: 10
        REACT_APP_POCKET_NETWORK_MAX_SESSIONS: 100
        REACT_APP_POCKET_NETWORK_REQUEST_TIMEOUT: 60000
        REACT_APP_POCKET_NETWORK_DISPATCHERS: https://node1.testnet.pokt.network:443
        REACT_APP_POCKET_NETWORK_TX_FEE: 100000
        REACT_APP_POCKET_NETWORK_CHAIN_ID: testnet-r1
        REACT_APP_POCKET_FREE_TIER_STAKE_AMOUNT: 20833330000
        REACT_APP_STAKE_DEFAULT_STATUS: Unstaked
        REACT_APP_DEFAULT_MAX_RELAYS_PER_DAY: 6912000
        REACT_APP_SECURE_LS_SECRET: ${{ secrets.REACT_APP_SECURE_LS_SECRET }}
        REACT_APP_PAYMENT_DEFAULT_CLIENT_ID: ${{ secrets.REACT_APP_PAYMENT_DEFAULT_CLIENT_ID }}
        REACT_APP_RECAPTCHA_CLIENT_KEY: ${{ secrets.REACT_APP_RECAPTCHA_CLIENT_KEY }}
        REACT_APP_POCKET_FREE_TIER_ACCOUNT: ${{ secrets.REACT_APP_POCKET_FREE_TIER_ACCOUNT }}
        REACT_APP_POCKET_FREE_TIER_ACCOUNT_PASSPRHASE: ${{ secrets.REACT_APP_POCKET_FREE_TIER_ACCOUNT_PASSPRHASE }}
      run: yarn build:prod
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: "frontend/build"
    - name: Clear CloudFront Cache
      uses: awact/cloudfront-action@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
  deploy:
    name: Backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: dashboard
        IMAGE_TAG: latest
        DATABASE_NAME: gateway-testnet
        POCKET_NETWORK_MAX_DISPATCHER: 7
        POCKET_NETWORK_REQUEST_TIMEOUT: 60000
        POCKET_NETWORK_MAX_SESSIONS: 1000000
        POCKET_NETWORK_SERVICE_WORKER_DATABASE_URL: redis://dashboard.js6zbp.ng.0001.usw2.cache.amazonaws.com:6379
        POCKET_NETWORK_SERVICE_WORKER_DELAYED_START_TIME: 50000
        POCKET_NETWORK_SERVICE_WORKER_ATTEMPTS: 10
        POCKET_FREE_TIER_STAKE_AMOUNT: 10000000
        POKT_MARKET_PRICE: 0.06
        POCKET_NETWORK_DISPATCHERS: https://node1.testnet.pokt.network:443,https://node2.testnet.pokt.network:443,https://node3.testnet.pokt.network:443,https://node4.testnet.pokt.network:443,https://node5.testnet.pokt.network:443,https://node6.testnet.pokt.network:443,https://node7.testnet.pokt.network:443
        POCKET_NETWORK_CHAIN_HASH: 0002
        POCKET_NETWORK_CHAIN_ID: testnet-r1
        POCKET_NETWORK_AAT_VERSION: 0.0.1
        POCKET_NETWORK_TRANSACTION_FEE: 10000000
        POCKET_FREE_TIER_MAX_RELAY_PER_DAY_AMOUNT: 10000000
        POCKET_NETWORK_PROVIDER_TYPE: HTTP
        POCKET_NETWORK_HTTP_PROVIDER_NODE: https://node1.testnet.pokt.network:443
        AUTH_PROVIDER_GITHUB_CALLBACK_URL: https://dashboard.pokt.network/api/auth/provider/github
        AUTH_PROVIDER_GOOGLE_CALLBACK_URL: https://dashboard.pokt.network/api/auth/provider/google
        EMAIL_FROM: dashboard@pokt.network
        CHECKOUT_DEFAULT_CURRENCY: USD
        CHECKOUT_MIN_RELAYS_PER_DAY: 433
        CHECKOUT_MAX_RELAYS_PER_DAY: 6912000
        CHECKOUT_MIN_VALIDATOR_POWER: 15000
        CHECKOUT_MAX_VALIDATOR_POWER: 1666666
        CHECKOUT_BASE_RELAY_PER_POKT: 0.12
        CHECKOUT_STABILITY: 0
        CHECKOUT_SESSIONS_PER_DAY: 3456
        CHECKOUT_P_RATE: 0.1
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./backend/
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: backend/ecs-task-definition.json
        container-name: dashboard
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: dashboard-service
        cluster: dashboard
        wait-for-service-stability: true

